### ISSUE TITLE
PHP warnings about undefined properties when editing entry

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-orbis-timesheets#13]
I recently stated getting the following error messages when editing an entry:

```
Warning: Undefined property: stdClass::$subscription_name in /wp-content/plugins/orbis-timesheets/includes/functions.php on line 135
```

https://github.com/pronamic/wp-orbis-timesheets/blob/24d765c3be4cb49f2e846f38ca191497e5ac0033/includes/functions.php#L135

```
Warning: Undefined property: stdClass::$principal_name in /wp-content/plugins/orbis-timesheets/templates/work_registration_fields.php on line 49
```

https://github.com/pronamic/wp-orbis-timesheets/blob/24d765c3be4cb49f2e846f38ca191497e5ac0033/templates/work_registration_fields.php#L49

**Comment by remcotolsma** [comment]
Somewhat fixed in https://github.com/pronamic/wp-orbis-timesheets/commit/344aac851ecc5964d09b15e085b16373f99fc587 and https://github.com/pronamic/wp-orbis-timesheets/commit/e7f645e9872b20c829b49079818e1f410d6ad294.
